##########################################################
# Voron Infinite Heatbed - Moonraker Configuration
# Add ONLY this line to your moonraker.conf:
#   [include ~/voron-infinite-heatbed/moonraker/infinite_heatbed.conf]
##########################################################

[include ~/voron-infinite-heatbed/mainsail/infinite_heatbed_panel.cfg]
